language: elixir
elixir:
  - '1.6.6'
otp_release:
  - '20.0'
matrix:
  include:
    - elixir: '1.7.3'
      otp_release: '21.0'
notifications:
  recipients:
    - travis@jeffweiss.org
    - matt@mattrobinson.net
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - "mix do deps.get, deps.compile, compile, test"
  - "mix dialyzer --halt-exit-status --format term"
